/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Customize folders page
 */
export interface FoldersPage {
  /**
   * Show the index as root folder. An index is a media source directory and is the parent of all its folders. By default only its subdirectories are listed
   */
  showIndex?: boolean;
  /**
   * Show a cover thumbnail of the folder. The cover is the first media of the folder or of its first subfolder. A media whose file name ends with '_cover' before its extension is preferred
   */
  showCover?: boolean;
  /**
   * Initial size of the folder thumbnails. Smaller thumbnails show more folders per row in the grid view and shorter rows in the list view. It is overruled by the size controls of the nav bar
   */
  thumbnailSize?: "xsmall" | "small" | "medium" | "large" | "xlarge";
  /**
   * Initial folder order. It is overruled by the order of the page
   */
  order?: "name" | "nameDesc";
  /**
   * Initial folder view. The list view shows the folder tree, the grid view shows all folders as squared cover thumbnails. It is overruled by the view toggle of the page
   */
  view?: "list" | "grid";
  [k: string]: unknown;
}
