/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Customize folders page
 */
export interface FoldersPage {
  /**
   * Show the index as root folder. An index is a media source directory and is the parent of all its folders. By default only its subdirectories are listed
   */
  showIndex?: boolean;
  [k: string]: unknown;
}
