/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Customize pages
 */
export interface Pages {
  disabled?: (("edit" | "date" | "video" | "map" | "tag" | "folder" | "all") | string)[];
  /**
   * Initial page of the webapp on its first load. It falls back to the page of all media if the configured page is disabled
   */
  landing?: "all" | "folders" | "years" | "tags" | "map";
  [k: string]: unknown;
}
