/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * List of plugin urls to load
 */
export type PluginUrls = string[];
/**
 * List of feature flags to disable. By default all features are enabled.
 *
 * The feature flags can also be disabled by query param 'disabled'
 */
export type FeatureFlags = (
  ("serverEvents" | "events" | "edit") | "database" | "pwa" | ("offlineDatabase" | "worker") | string
)[];
/**
 * List of downloadable media sources. This list will be injected from the server
 */
export type MediaSources = {
  downloadable?: boolean;
  indexName?: string;
  [k: string]: unknown;
}[];
export type MediaViewDisableFlags = (
  | ("detail" | "map" | "similar" | "annotation" | "edit" | "tag" | "share")
  | "nav"
)[];

/**
 * gallery configuration for webapp module
 */
export interface WebappConfig {
  webapp?: AppConfig;
  [k: string]: unknown;
}
/**
 * Configuration for webapp module
 */
export interface AppConfig {
  /**
   * Title of the webapp
   */
  title?: string;
  pluginManager?: PluginManager;
  disabled?: FeatureFlags;
  sources?: MediaSources;
  pages?: Pages;
  format?: FormatUtils;
  [k: string]: unknown;
}
export interface PluginManager {
  plugins?: PluginUrls;
  [k: string]: unknown;
}
/**
 * Customize pages
 */
export interface Pages {
  disabled?: (("edit" | "date" | "video" | "map" | "tag" | "folder" | "all") | string)[];
  /**
   * Initial page of the webapp on its first load. It falls back to the page of all media if the configured page is disabled
   */
  landing?: "all" | "folders" | "years" | "tags" | "map";
  folders?: FoldersPage;
  list?: ListPage;
  mediaView?: MediaViewPage;
  [k: string]: unknown;
}
/**
 * Customize folders page
 */
export interface FoldersPage {
  /**
   * Show the index as root folder. An index is a media source directory and is the parent of all its folders. By default only its subdirectories are listed
   */
  showIndex?: boolean;
  /**
   * Show a cover thumbnail of the folder. The cover is the first media of the folder or of its first subfolder. A media whose file name ends with '_cover' before its extension is preferred
   */
  showCover?: boolean;
  /**
   * Initial size of the folder thumbnails. Smaller thumbnails show more folders per row in the grid view and shorter rows in the list view. It is overruled by the size controls of the nav bar
   */
  thumbnailSize?: "xsmall" | "small" | "medium" | "large" | "xlarge";
  /**
   * Initial folder order. It is overruled by the order of the page
   */
  order?: "name" | "nameDesc";
  /**
   * Initial folder view. The list view shows the folder tree, the grid view shows all folders as squared cover thumbnails. It is overruled by the view toggle of the page
   */
  view?: "list" | "grid";
  [k: string]: unknown;
}
/**
 * Customize media lists
 */
export interface ListPage {
  /**
   * Layout of the media lists. 'fluent' keeps the aspect ratio of the media, 'grid' crops them to a grid of squares and 'list' shows one media per row with its file name beside its thumbnail. It is overruled by the layout toggle of the nav bar
   */
  thumbnails?: "list" | "grid" | "fluent";
  /**
   * Initial size of the thumbnails. Smaller thumbnails show more media per row. It is overruled by the size controls of the nav bar
   */
  thumbnailSize?: "xsmall" | "small" | "medium" | "large" | "xlarge";
  /**
   * Show the date scrollbar of media lists. It is placed at the right side of the list and jumps to the media of the selected date
   */
  scrollbar?: boolean;
  /**
   * Show the file name of every media below its thumbnail in the fluent and in the grid media list. The name is shown without its directory and with its file extension. The list layout shows it beside the thumbnail in any case
   */
  showFilename?: boolean;
  /**
   * Order of media lists without an explicit 'order by' expression in the search query. It is an order key with an optional direction, eg 'date asc', 'filesize desc' or 'count(tags) desc'. Supported keys are date, file, filename, updated, duration, width, height, filesize, random and count(files), count(tags), count(faces), count(objects)
   */
  defaultOrder?: string;
  [k: string]: unknown;
}
/**
 * Customize single media view
 */
export interface MediaViewPage {
  disabled?: MediaViewDisableFlags;
  /**
   * Start the video playback when a video is opened. Browsers can still block the autoplay until the site has user interaction
   */
  autoPlayVideo?: boolean;
  [k: string]: unknown;
}
/**
 * Date format as in linux date command
 *   %b month name
 *   %d day of month, eg 01
 *   %m month, eg 12
 *   %Y 4 full year, eg 2025
 *   %y 2-digit year, eg 25
 *   %a short weekday name, eg. Mon
 *   %A full weekday name, eg. Monday
 *   %H hour eg 18
 *   %I hour eg 06 (12-hour clock)
 *   %p am/AM
 *   %P AM/PM
 *   %M minute, eg 06
 *   %S seconds, eg 45
 */
export interface FormatUtils {
  /**
   * Date format
   */
  date?: string;
  /**
   * Month year format
   */
  monthYear?: string;
  /**
   * Year format
   */
  year?: string;
  /**
   * time format
   */
  time?: string;
  /**
   * time format with hour and minute
   */
  hourMinute?: string;
  [k: string]: unknown;
}
