/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Customize media lists
 */
export interface ListPage {
  /**
   * Shape of the thumbnails. 'fluent' keeps the aspect ratio of the media, 'square' crops them to a grid of squares. It is overruled by the layout toggle of the nav bar
   */
  thumbnails?: "fluent" | "square";
  /**
   * Initial size of the thumbnails. Smaller thumbnails show more media per row. It is overruled by the size controls of the nav bar
   */
  thumbnailSize?: "xsmall" | "small" | "medium" | "large" | "xlarge";
  /**
   * Show the date scrollbar of media lists. It is placed at the right side of the list and jumps to the media of the selected date
   */
  scrollbar?: boolean;
  /**
   * Show the file name of every media below its thumbnail in media lists. The name is shown without its directory and with its file extension
   */
  showFilename?: boolean;
  /**
   * Order of media lists without an explicit 'order by' expression in the search query. It is an order key with an optional direction, eg 'date asc', 'filesize desc' or 'count(tags) desc'. Supported keys are date, file, filename, updated, duration, width, height, filesize, random and count(files), count(tags), count(faces), count(objects)
   */
  defaultOrder?: string;
  [k: string]: unknown;
}
