/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Customize albums page
 */
export interface AlbumsPage {
  /**
   * Show the index as root album. An index is a media source directory and is the parent of all its albums. By default only its subdirectories are listed
   */
  showIndex?: boolean;
  /**
   * Show a cover thumbnail of the album. The cover is the first media of the album or of its first sub-album. A media whose file name ends with '_cover' before its extension is preferred
   */
  showCover?: boolean;
  /**
   * Initial size of the album thumbnails. Smaller thumbnails show more albums per row in the grid view and shorter rows in the list view. It is overruled by the size controls of the nav bar
   */
  thumbnailSize?: "xsmall" | "small" | "medium" | "large" | "xlarge";
  /**
   * Initial album order. It is overruled by the order of the page
   */
  order?: "name" | "nameDesc";
  /**
   * Initial album view. The list view shows the album tree, the grid view shows all albums as squared cover thumbnails. It is overruled by the view toggle of the page
   */
  view?: "list" | "grid";
  [k: string]: unknown;
}
