/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MediaViewDisableFlags = (("detail" | "map" | "similar" | "annotation" | "edit") | "nav")[];

/**
 * Customize single media view
 */
export interface MediaViewPage {
  disabled?: MediaViewDisableFlags;
  /**
   * Start the video playback when a video is opened. Browsers can still block the autoplay until the site has user interaction
   */
  autoPlayVideo?: boolean;
  [k: string]: unknown;
}
